language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
before_install:
  - cd ..
  - curl -L -O http://sourceforge.net/projects/pyqt/files/sip/sip-4.16.5/sip-4.16.5.tar.gz
  - tar -xvf sip-4.16.5.tar.gz
  - cd sip-4.16.5
  - python configure.py
  - make -j 4
  - sudo make install
  - cd ..
  - curl -L -O http://sourceforge.net/projects/pyqt/files/PyQt4/PyQt-4.11.3/PyQt-x11-gpl-4.11.3.tar.gz
  - tar -xvf PyQt-x11-gpl-4.11.3.tar.gz
  - cd PyQt-x11-gpl-4.11.3
  - python configure.py --confirm-license
  - make -j 4
  - sudo make install
  - cd ../OpenSCAD2D
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
install: "pip install -r requirements.txt --use-mirrors"
script:  python test.py
notifications:
  email:
    - sven@fablab-karlsruhe.de