language: python
python:
  - "2.6"
  - "2.7"
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
install:
  - sudo apt-get install libqt4-dev
  - pip install pyside
  - "pip install -r requirements.txt --index-url"
  - pip install coveralls
script:  
  - "python test.py"
  - "coverage run test.py"
after_success:
  - coveralls
notifications:
  email:
    - sven@fablab-karlsruhe.de
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/1cc3163a67a5bcdc1aca
    on_success: change  # options: [always|never|change] default: always
